name: final_project
channels:
  - defaults
dependencies:
  - matplotlib=2.2.2
  - seaborn
  - numpy=1.15.0
  - pip=10.0.1
  - python=3.6.6
  - scipy=1.3.2
  - scikit-learn=0.21.3
  - biopython=1.75
  - numba
  - boto3
  - tqdm
  - ipython 
  - pillow
