name: final_project
channels:
  - defaults
dependencies:
  - matplotlib
  - seaborn
  - numpy
  - pip
  - python=3.6.6
  - jupyter
  - jupyterlab
  - scipy
  - scikit-learn
  - biopython
  - numba
  - boto3
  - tqdm
  - ipython 
  - pillow
